language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm


install:
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
  - composer self-update
  - mkdir -p build/logs


script:
  #PHPUnit
  - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml

after_success:
# Submit coverage report to Coveralls servers, see .coveralls.yml
 - travis_retry php coveralls.phar -v

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true
